
# FIXME: set production to install from tar

ifeq ($(MAKECMDGOALS),)
# Set default target for CI environments:
ifeq ($(ENV),development)
DEFAULT ?= .cli-version-update
endif
ifeq ($(ENV),testing)
DEFAULT ?=
endif
ifeq ($(ENV),production)
DEFAULT ?= build
endif
endif

ifeq ($(MAKECMDGOALS),test)
ifneq ($(ENV),development)
TEST += test-run
endif
ifeq ($(ENV),testing)
TEST += .cli-version-update cli-version-check
endif
endif

