 
# Id: git-versioning/0.0.8-master package.yaml
# Start

- type: application/x-project-mpe
  id: git-versioning
  version: 0.0.8
  environments: [ 'development' ]

# End
# Id: git-versioning/0.0.8-master package.yaml







