# Id: git-versioning/0.2.10-dev package.yaml
# Start

- type: application/vnd.dotmpe.project
  main: git-versioning
  id: git-versioning
  version: 0.2.10-dev # git-versioning
  environments: [ 'development' ]

  scripts:
    init: 
      - Build_Deps_Default_Paths=1 ./install-dependencies.sh all
    check:
      - git-versioning check
      - bats -c test/*-spec.bats
      - bats test/git-versioning-spec.bats
    test:
      - bats test/*-spec.bats
    sync-lib:
      - ./tools/sh/sync-lib.sh
  pd-meta:
    #check: ":make:git-pre-commit"
    check: ":vchk :bats-specs :bats:test/git-versioning-spec.bats"
    test: ":bats"
    git-hooks:
      pre-commit: ./tools/git-hooks/pre-commit.sh
    init: "./install-dependencies.sh all"

# git-versioning main: git-versioning

# End
